# Generated by Django 5.0.6 on 2024-08-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_is_read_messages_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='type',
            field=models.CharField(default='text_message', max_length=100),
        ),
    ]
