# Generated by Django 5.0.6 on 2024-08-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='type',
            new_name='message_type',
        ),
    ]
